# Generated by Django 4.0.1 on 2022-01-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Блюдо', max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Продукт', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price_per_kg', models.FloatField()),
                ('evaluation', models.TextField()),
                ('permission_flag', models.BooleanField(default=True)),
                ('product', models.ForeignKey(default='Nope', on_delete=django.db.models.deletion.CASCADE, to='ol.product', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='DishComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=0)),
                ('dish', models.ForeignKey(default='отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.dish', to_field='name')),
                ('product', models.ForeignKey(default='отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.product', to_field='name')),
            ],
        ),
    ]
