# Generated by Django 4.0.1 on 2022-01-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0002_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(default='без описания'),
        ),
    ]
