# Generated by Django 4.0.1 on 2022-01-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0003_alter_dish_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcomponent',
            name='product',
            field=models.OneToOneField(default='отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.product', to_field='name'),
        ),
    ]
