# Generated by Django 4.0.1 on 2022-01-11 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0006_alter_dishcomponent_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishcomponent',
            old_name='dish',
            new_name='ref_dish',
        ),
        migrations.RemoveField(
            model_name='dishcomponent',
            name='product',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='product',
        ),
        migrations.AddField(
            model_name='dishcomponent',
            name='dish_product',
            field=models.ForeignKey(default='отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.product', to_field='name'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_product',
            field=models.ForeignKey(default='Nope', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.product', to_field='name'),
        ),
    ]
