# Generated by Django 4.0.1 on 2022-01-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0007_rename_dish_dishcomponent_ref_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishcomponent',
            name='dish_product',
            field=models.ForeignKey(default='Отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.product', to_field='name'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_product',
            field=models.ForeignKey(default='Отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.product', to_field='name'),
        ),
    ]
