# Generated by Django 4.0.1 on 2022-01-11 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0008_alter_dishcomponent_dish_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishcomponent',
            old_name='ref_dish',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dishcomponent',
            old_name='dish_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='goods_product',
            new_name='product',
        ),
    ]
