# Generated by Django 4.0.1 on 2022-01-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0009_rename_ref_dish_dishcomponent_dish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishcomponent',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishcomponent',
            name='dish',
            field=models.ManyToManyField(default='Отсутствует', to='ol.Dish'),
        ),
    ]
