# Generated by Django 4.0.1 on 2022-01-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ol', '0010_remove_dishcomponent_dish_dishcomponent_dish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishcomponent',
            name='dish',
        ),
        migrations.AddField(
            model_name='dishcomponent',
            name='dish',
            field=models.ForeignKey(default='Отсутствует', on_delete=django.db.models.deletion.SET_DEFAULT, to='ol.dish', to_field='name'),
        ),
    ]
